/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root.tsx";
import { Route as IndexRouteImport } from "./routes/index.tsx";
import { Route as LoginRouteImport } from "./routes/login.tsx";
import { Route as Oauth2AuthRouteImport } from "./routes/oauth2.auth.tsx";
import { Route as Oauth2DeviceRouteImport } from "./routes/oauth2.device.tsx";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const Oauth2AuthRoute = Oauth2AuthRouteImport.update({
  id: "/oauth2/auth",
  path: "/oauth2/auth",
  getParentRoute: () => rootRouteImport,
} as any);
const Oauth2DeviceRoute = Oauth2DeviceRouteImport.update({
  id: "/oauth2/device",
  path: "/oauth2/device",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/oauth2/auth": typeof Oauth2AuthRoute;
  "/oauth2/device": typeof Oauth2DeviceRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/oauth2/auth": typeof Oauth2AuthRoute;
  "/oauth2/device": typeof Oauth2DeviceRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/oauth2/auth": typeof Oauth2AuthRoute;
  "/oauth2/device": typeof Oauth2DeviceRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/login" | "/oauth2/auth" | "/oauth2/device";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/login" | "/oauth2/auth" | "/oauth2/device";
  id: "__root__" | "/" | "/login" | "/oauth2/auth" | "/oauth2/device";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  LoginRoute: typeof LoginRoute;
  Oauth2AuthRoute: typeof Oauth2AuthRoute;
  Oauth2DeviceRoute: typeof Oauth2DeviceRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/oauth2/auth": {
      id: "/oauth2/auth";
      path: "/oauth2/auth";
      fullPath: "/oauth2/auth";
      preLoaderRoute: typeof Oauth2AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/oauth2/device": {
      id: "/oauth2/device";
      path: "/oauth2/device";
      fullPath: "/oauth2/device";
      preLoaderRoute: typeof Oauth2DeviceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  Oauth2AuthRoute: Oauth2AuthRoute,
  Oauth2DeviceRoute: Oauth2DeviceRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.ts";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
